### GET Productos
GET http://localhost:5000/api/v1/productos

### Get Producto by id
GET http://localhost:5000/api/v1/productos/7

### POST producto
POST http://localhost:5000/api/v1/productos
Content-Type: application/json

{
  "nombre" : "aaa",
  "descripcion": "descripcion9",
  "imagen": "https://i.pinimg.com/736x/13/82/43/138243ffb07290e9bd1a1d612a929e7e.jpg",
  "precio": 152.88,
  "stock": true
}

### UPDATE Product
PUT http://localhost:5000/api/v1/productos/13
Content-Type: application/json

{
  "nombre": "Lucy",
  "descripcion": "aaaaaaaaa"
}

### DELETE Product
DELETE http://localhost:5000/api/v1/productos/13